#!/usr/bin/env bash
# Transfers a file from our client to a server
#
# variables
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assigning paramenters to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# desabling strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Checking if the ftransfer was successful
if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFER SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILED"
fi
