#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo pt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend  MarwaneMLE
        bind *:80
        mode http
        default_backend app

backend app
        balance roundrobin
        server 429900-web-01 35.175.132.176:80 check
        server 429900-web-02 100.25.17.94:80 check" >> /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
