#!/usr/bin/env bash
# This is a script that displays to infinity and beyond indefinitely,
# and 'I am invincible!!!'  when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true
do
	echo "to infinity and beyond"
	sleep 2
done
