#!/usr/bin/env bash
# Display the content of the current working directory,
# showing only the part of the name after the first dash.

for file in *; do
    # Check if the file is not a hidden file
    if [[ ! $file == .* ]]; then
        # Use cut to extract the part of the name after the first dash
        display_name=$(echo "$file" | cut -d'-' -f2-)
        echo "$display_name"
    fi
done
