#!/usr/bin/env bash
# Display the content of the current working directory,
# showing only the part of the name after the first dash.

input="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d':' --fields=1,3,6
done < "$input"
